import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/providers/sessionProvider";
import ReduxProvider from "@/providers/reduxProvider";
import { Poppins } from "next/font/google"


const PoppinsFont = Poppins({
  weight: ["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900" ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ fontFamily: PoppinsFont.style.fontFamily   }}
      >
        <ReduxProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ReduxProvider>

      </body>
    </html>
  );
}
